services:
  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=travel
      - MYSQL_DATABASE=travel_db
    volumes:
      - db-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ptravel"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  db-data:
